server:
  port: 8888

grpc:
  server:
    port: 50051

spring:
  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  excluded:
    path-list:
      /api/members/login,
      /api/members/refresh_token

jwt:
  prefix: 'Bearer '
  access-token-header: Authorization
  refresh-token-header: AuthorizationRefresh
  access-token-TTL: 300
  refresh-token-TTL: 259200
  public-key-location: ${PUBLIC_KEY_PATH}
  private-key-location: ${PRIVATE_KEY_PATH}

cookie:
  refresh-token:
    cookie-name: Refresh
    limit-time: 259200
    accepted-url: /api/members/refresh_token
    domain: localhost
    http-only: true
